#ARENA SETTINGS
HOST = "mqtt.arenaxr.org"
NAMESPACE = "johnchoi"
SCENE = "NPC"

#DIALOGUE TREE FILE
DIALOGUE_FILENAME = "cartoon_dialogue.json"

#NPC (name Alphanumeric only plus _)
NPC_NAME = "NPC_cactus"
NPC_GLTF_URL = "/store/users/johnchoi/Characters/Cactus/Cactus.gltf"

#COLLISION ENTER NODE
COLLISION_ENTER_NODE = "Enter"
COLLISION_EXIT_NODE = "Exit"
COLLIDER_SCALE = (2,4,2)
COLLIDER_COLOR = (50,50,216)
COLLIDER_OPACITY = 0.1

#NPC ROOT TRANSFORM
NPC_SCALE = (2,2,2)
NPC_START_POSITION = (2,0,0)
NPC_START_ROTATION = (0,0,0)
#NPC DEBUG CUBE
NPC_CUBE_COLOR = (255,100,16)
NPC_CUBE_OPACITY = 0.3

#NPC GLTF TRANSFORM
NPC_GLTF_SCALE = (1,1,1)
NPC_GLTF_POSITION = (0,0,0)
NPC_GLTF_ROTATION = (0,180,0)

#SPEECH SETTINGS
SPEECH_TEXT_COLOR = (100,100,100)
SPEECH_TEXT_POSITION = (0,1,0)
SPEECH_TEXT_SCALE = (0.4,0.4,0.4)

#CHOICE SETTINGS
CHOICE_TEXT_COLOR = (0,0,0)
CHOICE_BUBBLE_COLOR = (200,200,200)
CHOICE_BUBBLE_POSITION = (0,0.2,0.6)
CHOICE_BUBBLE_OFFSET_Y = 0.1